name: Github Pages Deploy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Code linting
        run: yarn lint

      - name: Type checking
        run: yarn tsc
